### ISSUE TITLE
Refresh Token

### ISSUE THREAD

**Issue by johnpoth** [keycloak/openshift-integration#20]
Awesome set of scripts! Tried it out and works flawlessly.

Is it possible to easily extend the setup to be able to use a refresh-token and [client certificates](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#option-1-oidc-authenticator)? Thanks!

**Comment by stianst** [comment]
Unless OpenShift has recently added support for refresh tokens that wouldn't work. On the flip-side though OpenShift always checks the token via the token review endpoint and the tokens are also signed so they can only be verified by Keycloak itself.

With client certificates do you mean authenticate users with a x509 cert rather than username/password? Keycloak supports that and it will work fine when you login to OpenShift web console, but not sure about `oc login`. The latter will probably not work at the moment.

**Comment by johnpoth** [comment]
Ah thanks @stianst for the info! Closing the issue...
